// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHome.backend.Data;

#nullable disable

namespace smartHome.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241206103503_AddHouseApartmentComplex")]
    partial class AddHouseApartmentComplex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartHome.backend.Models.Apartment", b =>
                {
                    b.Property<int>("ApartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApartmentId"));

                    b.Property<int>("ApartmentComplexId")
                        .HasColumnType("int");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApartmentId");

                    b.HasIndex("ApartmentComplexId");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("SmartHome.backend.Models.ApartmentComplex", b =>
                {
                    b.Property<int>("ApartmentComplexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApartmentComplexId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApartmentComplexId");

                    b.ToTable("ApartmentComplexes");
                });

            modelBuilder.Entity("SmartHome.backend.Models.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<int?>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<double>("EnergyConumptionRate")
                        .HasColumnType("float");

                    b.Property<int?>("HouseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeviceId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("HouseId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("SmartHome.backend.Models.EnergyData", b =>
                {
                    b.Property<int>("EnergyDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnergyDataId"));

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalEnergyConsumed")
                        .HasColumnType("float");

                    b.HasKey("EnergyDataId");

                    b.ToTable("EnergyData");
                });

            modelBuilder.Entity("SmartHome.backend.Models.House", b =>
                {
                    b.Property<int>("houseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("houseId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("houseId");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("SmartHome.backend.Models.Apartment", b =>
                {
                    b.HasOne("SmartHome.backend.Models.ApartmentComplex", "ApartmentComplex")
                        .WithMany("Apartments")
                        .HasForeignKey("ApartmentComplexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApartmentComplex");
                });

            modelBuilder.Entity("SmartHome.backend.Models.Device", b =>
                {
                    b.HasOne("SmartHome.backend.Models.Apartment", "Apartment")
                        .WithMany("Devices")
                        .HasForeignKey("ApartmentId");

                    b.HasOne("SmartHome.backend.Models.House", "House")
                        .WithMany("Devices")
                        .HasForeignKey("HouseId");

                    b.Navigation("Apartment");

                    b.Navigation("House");
                });

            modelBuilder.Entity("SmartHome.backend.Models.Apartment", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("SmartHome.backend.Models.ApartmentComplex", b =>
                {
                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("SmartHome.backend.Models.House", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
